# Generated by Django 6.0.5 on 2026-05-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(blank=True, default='', max_length=60)),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('campus_id', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'verbose_name': 'University Campus',
                'verbose_name_plural': 'University Campuses',
            },
        ),
    ]
