# Generated by Django 3.0.8 on 2020-07-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='starting_balance',
            new_name='initial_deposit',
        ),
    ]
