# Generated by Django 3.0.8 on 2020-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_auto_20200714_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=10),
        ),
    ]
